// <auto-generated />
using System;
using Cooperative_Financing.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cooperative_Financing.Migrations
{
    [DbContext(typeof(CooperativeContext))]
    [Migration("20250211033951_FixPaymentTable")]
    partial class FixPaymentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Cooperative_Financing.Models.DataUsers", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<bool>("Is_Admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Member_Id")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("User_Id");

                    b.HasIndex("Member_Id");

                    b.ToTable("DataUsers");
                });

            modelBuilder.Entity("Cooperative_Financing.Models.Loans", b =>
                {
                    b.Property<int>("Loan_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Loan_Id"));

                    b.Property<float>("Annual_Interest")
                        .HasColumnType("float");

                    b.Property<DateTime>("End_Month")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("First_Month")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Loan_Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Member_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Monthly_Payment")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Purpose_Loan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Release_Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_Payment")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Loan_Id");

                    b.HasIndex("Member_Id");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("Cooperative_Financing.Models.Members", b =>
                {
                    b.Property<int>("Member_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Member_Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Contribution")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("date");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Member_Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Cooperative_Financing.Models.Payments", b =>
                {
                    b.Property<int>("Payment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Payment_Id"));

                    b.Property<int>("Loan_Id")
                        .HasColumnType("int");

                    b.Property<int>("Member_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Payment_Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Payment_Date")
                        .HasColumnType("date");

                    b.HasKey("Payment_Id");

                    b.HasIndex("Loan_Id");

                    b.HasIndex("Member_Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Cooperative_Financing.Models.DataUsers", b =>
                {
                    b.HasOne("Cooperative_Financing.Models.Members", "Member")
                        .WithMany()
                        .HasForeignKey("Member_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Cooperative_Financing.Models.Loans", b =>
                {
                    b.HasOne("Cooperative_Financing.Models.Members", null)
                        .WithMany()
                        .HasForeignKey("Member_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cooperative_Financing.Models.Payments", b =>
                {
                    b.HasOne("Cooperative_Financing.Models.Loans", null)
                        .WithMany()
                        .HasForeignKey("Loan_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cooperative_Financing.Models.Members", null)
                        .WithMany()
                        .HasForeignKey("Member_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
